# Project 
site_name: Rustunite
site_url: https://rustunite.com/
site_author: Rustunite
site_description: >-
  Rustunite — A EU Rust game server network built by the community for the community.

# Repository
repo_name: rustunite/wiki
repo_url: https://github.com/rustunite/wiki
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Newgent Digital. All rights reserved.

# Theme
theme:
  name: material
  language: en
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/eye
        name: Switch to light mode
  font:
    text: Inter
    code: IBM Plex Mono

# Plugins
plugins:
  - search

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.rustunite.com/

# Markdown Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

# Pages
nav:
  - Home: index.md
